apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: tuttle
  labels:
    component: tuttle
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  type: NodePort
  selector:
    component: tuttle
